// 2025-2026 School Spelling Bee Study List
// Scripps National Spelling Bee - Word Club

const ONE_BEE = [
  // IMG_6594 - Page 1
  "tag", "send", "deck", "stuck", "snug", "fish", "hold", "mind", "stay", "scrub",
  "draw", "brown", "cozy** OR cosy", "tint", "milk", "yawn", "tank", "want", "crowd",
  "pond", "skirt", "sharks", "quilt", "twigs", "taffy", "comfy", "stretch", "tight",
  "candy", "scrunch", "ruby", "close", "tackle", "wire", "skater", "giant", "bucket",
  "chance", "baskets", "tender", "paste", "melon", "farmer", "parent", "tail", "hockey",
  "slime", "insects", "teeth", "shortcut", "bait", "lure", "cluster", "forest", "hollow",
  "spinning", "baffling", "sizzling", "hoist", "search", "remind", "mango", "coral",
  "jangle", "shimmer", "blossoms", "swampy", "studded", "focus", "distress", "lessons",
  "moment", "ajar", "basil", "triple", "satin", "ahoy", "signal", "answer", "shuffle",
  "dollop", "minnows", "silver", "before", "circus", "writing", "kitchen", "sugar",
  "awkward", "seep", "sweet", "wheels", "faint", "fruit", "roam",
  // IMG_6595 - Page 2
  "goats", "woozy", "limbs", "ahead", "unicorn", "faraway", "heater", "pirates",
  "understand", "wooden", "leaning", "breakfast", "window", "acrobat", "message",
  "chocolate", "forepaw", "elephant", "hedgehog", "recipe", "garbage", "surprise",
  "mermaid", "bombarded", "disability", "incredible", "leather", "countess", "nervous",
  "peppercorn", "cartwheel", "raise", "weather", "zooming", "attacked", "turnout",
  "eaten", "streetlights", "journey", "courtyard", "shouting", "asleep", "curious",
  "dinosaur", "brilliant", "vacuum", "gorgeous", "monsoon", "dangerous", "avocado",
  "valentine", "February", "formation", "especially"
];

const TWO_BEE = [
  // IMG_6596
  "hesitate", "scorcher", "scavenger", "fragments", "deflated", "unleash", "ration",
  "cosmetics", "crawdad", "frustration", "unruly", "mascot", "aroma",
  "moustache** OR mustache", "artifacts** OR artefacts", "perfume", "sinister", "tuxedo", "discoveries",
  "lurches", "language", "prognosis", "Buffalo", "sequins", "gallop", "fabulous",
  "lanky", "fluently", "mysterious", "brandished", "sardines", "anguish", "conical",
  "rickety", "lilt", "pediatric", "porridge", "democracy", "rummage", "beige",
  "ancestral", "grimace", "gaunt", "enormous", "geranium", "nautical", "dubious",
  "ebony", "foreign", "paltry", "verdict", "garbled", "encourages", "imitation",
  "miniature", "receptionist", "preamble", "plausible", "reprimanding", "commotion",
  "oblivion", "immigrants", "steeple", "spectators", "lanyards", "suspicious",
  "parchment", "ramshackle", "fugitive", "heron", "dissolving", "nomad", "billowed",
  "skewer", "Berlin", "lunacy", "conjure", "bracken", "noggin", "neon", "rakish",
  "hypnosis", "rotunda", "gusto", "toiletries", "gleaned", "jeered", "winsome",
  "prattling", "galore", "emporium", "atrium", "eccentric", "savant"
];

const THREE_BEE = [
  // IMG_6597 - Page 1
  "almanac", "hippies", "samosas", "campaign", "pistachio", "mosque", "zombielike",
  "warlock", "colossus", "convulsively", "dimensional", "garishly", "graffitist",
  "Everest", "dexterity", "cavorting", "marauder", "conscience", "battlements",
  "deferential", "albatross", "khaki", "opalescent", "asphalt", "Yiddish", "talcum",
  "tranquilizer", "equestrian", "plaited", "monsieur", "manticores", "prestigious",
  "fraidycat", "guttural", "lo mein", "courier", "sans serif", "psyche", "stucco",
  "Frankenstein", "schema", "et cetera", "vidimus", "delphine", "slough", "archipelago",
  "serape** OR sarape", "puissance", "pinioning", "chignon", "pheromone", "galleon",
  "magnanimous", "chartreuse", "wainscoting", "Nehru",
  // IMG_6598 - Page 2
  "gangly", "swaggering", "chimneys", "riveted", "plaid", "dirge", "zeal", "whittled",
  "depots", "fiberglass", "salvaged", "fissures", "enthusiastic", "discipline",
  "unfamiliar", "scurrying", "dignitaries", "pizzeria", "dismissal", "skittish",
  "careened", "nomination", "opportunist", "dictatorship", "comrades", "sporadic",
  "promenade", "repugnant", "invincible", "renowned", "parachute", "laborious",
  "appointment", "foreseeable", "ratify", "scalpel", "reclusive", "compassionate",
  "bulletin", "alfalfa", "officially", "crematorium", "bayonet", "amicable", "exuberant",
  "beautician", "equations", "assignment", "ultimatum", "whinnying", "squalor",
  "memoirs", "cylinders", "ominous", "muffler", "syndrome", "premises", "safari",
  "lasagna", "substantially", "mercantile", "formidable", "propaganda", "marquee",
  "proficient", "compunction", "emphatically", "hyperventilated", "ostracism",
  "onslaught", "ruefully", "misanthrope", "prototype", "cravenly", "mulberry",
  "hypocritical", "chlorine", "traumatic", "receipts", "solemnly", "begrudge",
  "contentious", "precocious", "ensemble", "cadre", "lye", "belfry", "lacrosse",
  "sluice", "cajolery", "vigilance", "residuals", "boutique", "peroxide", "aristocracy",
  "apocalypse",
  // IMG_6599 - Page 3
  "tuberculosis", "barricade", "confreres", "anonymously", "unparalleled", "barrette",
  "chassis", "junket", "quandary", "Erie", "gingham", "silhouette", "auxiliary",
  "thesaurus", "patriarchs", "chandelier", "dulce", "concierge", "latticework",
  "hibiscus", "tamale", "maracas", "gyroplane", "burpees", "Adriatic", "piccolo",
  "au revoir", "tulle", "boll weevil", "camphor", "Tucson", "paparazzi", "pumpernickel",
  "pogrom", "bursitis", "cycads", "sarsaparilla", "cannelloni", "boulangerie",
  "bronchitis", "Oswego", "diphtheria", "baklava", "corbels", "trebuchets", "Kilimanjaro",
  "protege", "hors d'oeuvres", "maquisards", "Aubusson", "Charolais** OR Charollais"
];

// Sentences for each word (4th grade appropriate)
const WORD_SENTENCES = {
  // ONE BEE words
  "tag": "We played tag at recess until the bell rang.",
  "send": "I will send a letter to my grandmother.",
  "deck": "We built a wooden deck behind our house.",
  "stuck": "My shoe got stuck in the mud.",
  "snug": "The kitten curled up in a snug blanket.",
  "fish": "We caught a big fish at the lake.",
  "hold": "Please hold the door open for me.",
  "mind": "I don't mind if you borrow my pencil.",
  "stay": "Can you stay for dinner tonight?",
  "scrub": "I need to scrub the dirt off my hands.",
  "draw": "I like to draw pictures of animals.",
  "brown": "The dog has brown fur and floppy ears.",
  "cozy": "My bed is cozy and warm on cold nights.",
  "tint": "The sunset gave the sky a pink tint.",
  "milk": "I drink a glass of milk every morning.",
  "yawn": "I had to yawn because I was so sleepy.",
  "tank": "The fish tank has colorful tropical fish.",
  "want": "I want to learn how to play guitar.",
  "crowd": "A large crowd gathered for the parade.",
  "pond": "Ducks swim in the pond behind our school.",
  "skirt": "She wore a blue skirt to the party.",
  "sharks": "Sharks have very sharp teeth.",
  "quilt": "Grandma made a beautiful quilt for my bed.",
  "twigs": "Birds use twigs to build their nests.",
  "taffy": "We pulled saltwater taffy at the beach.",
  "comfy": "These new shoes are really comfy.",
  "stretch": "Always stretch before you exercise.",
  "tight": "These jeans are too tight around my waist.",
  "candy": "We only eat candy on special occasions.",
  "scrunch": "I scrunch up my face when I taste something sour.",
  "ruby": "The queen wore a ruby necklace.",
  "close": "Please close the window because it's cold.",
  "tackle": "The football player made a great tackle.",
  "wire": "The electrician fixed the broken wire.",
  "skater": "The ice skater performed a triple jump.",
  "giant": "The giant in the story lived in a castle.",
  "bucket": "I filled the bucket with water.",
  "chance": "Everyone deserves a second chance.",
  "baskets": "We made baskets to hold Easter eggs.",
  "tender": "The steak was tender and delicious.",
  "paste": "I used paste to glue my project together.",
  "melon": "Watermelon is my favorite summer melon.",
  "farmer": "The farmer grows corn and wheat.",
  "parent": "My parent helped me with my homework.",
  "tail": "The dog wagged its tail happily.",
  "hockey": "My brother plays hockey every Saturday.",
  "slime": "We made green slime in science class.",
  "insects": "Insects have six legs and antennae.",
  "teeth": "You should brush your teeth twice a day.",
  "shortcut": "We took a shortcut through the park.",
  "bait": "Dad put bait on the fishing hook.",
  "lure": "The shiny lure attracted many fish.",
  "cluster": "A cluster of grapes hung from the vine.",
  "forest": "We went hiking in the forest.",
  "hollow": "The squirrel lived in a hollow tree.",
  "spinning": "The top kept spinning for a long time.",
  "baffling": "The magic trick was baffling to everyone.",
  "sizzling": "The bacon was sizzling in the pan.",
  "hoist": "They used a crane to hoist the heavy beam.",
  "search": "We had to search the whole house for the keys.",
  "remind": "Please remind me to return my library book.",
  "mango": "The mango tasted sweet and tropical.",
  "coral": "The coral reef was full of colorful fish.",
  "jangle": "The keys jangle when you shake them.",
  "shimmer": "The lake began to shimmer in the sunlight.",
  "blossoms": "Cherry blossoms bloom every spring.",
  "swampy": "The swampy area was full of frogs.",
  "studded": "Her crown was studded with diamonds.",
  "focus": "I need to focus on my math test.",
  "distress": "The lost puppy was in distress.",
  "lessons": "I take piano lessons every Tuesday.",
  "moment": "Wait just a moment while I get ready.",
  "ajar": "The door was left slightly ajar.",
  "basil": "Mom adds fresh basil to her pasta sauce.",
  "triple": "I ordered a triple scoop ice cream cone.",
  "satin": "The bride wore a beautiful satin dress.",
  "ahoy": "The pirate shouted ahoy from the ship.",
  "signal": "The traffic signal turned green.",
  "answer": "Please answer the question correctly.",
  "shuffle": "Shuffle the cards before we play.",
  "dollop": "Add a dollop of whipped cream on top.",
  "minnows": "We saw tiny minnows in the stream.",
  "silver": "The silver jewelry sparkled in the light.",
  "before": "Wash your hands before eating dinner.",
  "circus": "The circus had amazing acrobats.",
  "writing": "I enjoy writing stories in my journal.",
  "kitchen": "Mom is cooking dinner in the kitchen.",
  "sugar": "Don't add too much sugar to your cereal.",
  "awkward": "It was awkward when I forgot her name.",
  "seep": "Water began to seep through the crack.",
  "sweet": "The apple pie tasted sweet and delicious.",
  "wheels": "The car has four wheels.",
  "faint": "I felt faint after running so fast.",
  "fruit": "Eating fruit is good for your health.",
  "roam": "The cattle roam freely in the meadow.",
  "goats": "The goats climbed up the rocky hill.",
  "woozy": "I felt woozy after spinning in circles.",
  "limbs": "The tree's limbs swayed in the wind.",
  "ahead": "Look ahead to see where you're going.",
  "unicorn": "The unicorn had a magical golden horn.",
  "faraway": "She dreamed of visiting faraway lands.",
  "heater": "The heater keeps our house warm.",
  "pirates": "Pirates sailed the seas looking for treasure.",
  "understand": "I understand how to solve this problem.",
  "wooden": "We sat on a wooden bench in the park.",
  "leaning": "The old tower was leaning to one side.",
  "breakfast": "I eat breakfast every morning before school.",
  "window": "Please open the window for fresh air.",
  "acrobat": "The acrobat flew through the air with grace.",
  "message": "I sent a message to my friend.",
  "chocolate": "I love chocolate cake for my birthday.",
  "forepaw": "The cat lifted its forepaw to swat at the toy.",
  "elephant": "The elephant sprayed water from its trunk.",
  "hedgehog": "The hedgehog curled into a ball.",
  "recipe": "Grandma shared her secret cookie recipe.",
  "garbage": "Please take out the garbage tonight.",
  "surprise": "The party was a complete surprise.",
  "mermaid": "The mermaid swam through the ocean waves.",
  "bombarded": "We were bombarded with questions after the game.",
  "disability": "A disability does not define a person.",
  "incredible": "The sunset view was absolutely incredible.",
  "leather": "Dad has a leather wallet.",
  "countess": "The countess lived in a grand mansion.",
  "nervous": "I felt nervous before my presentation.",
  "peppercorn": "Add a peppercorn to season the soup.",
  "cartwheel": "She did a perfect cartwheel across the grass.",
  "raise": "Please raise your hand if you have a question.",
  "weather": "The weather is sunny and warm today.",
  "zooming": "The race cars were zooming around the track.",
  "attacked": "The knights attacked the castle walls.",
  "turnout": "The turnout for the concert was amazing.",
  "eaten": "I have already eaten lunch.",
  "streetlights": "The streetlights came on at dusk.",
  "journey": "Our journey took us across three states.",
  "courtyard": "The courtyard had a beautiful fountain.",
  "shouting": "Stop shouting and use your indoor voice.",
  "asleep": "The baby fell asleep in my arms.",
  "curious": "The curious kitten explored every room.",
  "dinosaur": "The dinosaur skeleton was huge.",
  "brilliant": "She had a brilliant idea for the project.",
  "vacuum": "I need to vacuum my bedroom carpet.",
  "gorgeous": "The sunset was absolutely gorgeous.",
  "monsoon": "The monsoon brought heavy rains.",
  "dangerous": "Swimming in the ocean can be dangerous.",
  "avocado": "I added avocado to my sandwich.",
  "valentine": "I made a valentine card for my mom.",
  "February": "February is the shortest month of the year.",
  "formation": "The geese flew in a V formation.",
  "especially": "I love all fruits, especially strawberries.",

  // TWO BEE words
  "hesitate": "Don't hesitate to ask for help.",
  "scorcher": "Today is a real scorcher at over 100 degrees.",
  "scavenger": "The scavenger hunt was so much fun.",
  "fragments": "Fragments of the broken vase were everywhere.",
  "deflated": "The balloon deflated overnight.",
  "unleash": "We unleash our creativity in art class.",
  "ration": "During the war, people had to ration food.",
  "cosmetics": "The store sells cosmetics like lipstick.",
  "crawdad": "We caught a crawdad in the creek.",
  "frustration": "I felt frustration when I couldn't solve the puzzle.",
  "unruly": "The unruly crowd made too much noise.",
  "mascot": "Our school mascot is a tiger.",
  "aroma": "The aroma of fresh bread filled the kitchen.",
  "moustache": "My grandfather has a gray moustache.",
  "artifacts": "The museum displays ancient artifacts.",
  "perfume": "Mom's perfume smells like roses.",
  "sinister": "The villain had a sinister laugh.",
  "tuxedo": "He wore a tuxedo to the wedding.",
  "discoveries": "Scientists make amazing discoveries every day.",
  "lurches": "The old bus lurches forward when it starts.",
  "language": "I am learning a new language.",
  "prognosis": "The doctor gave a positive prognosis.",
  "Buffalo": "Buffalo roam across the plains.",
  "sequins": "Her dress was covered in sparkly sequins.",
  "gallop": "The horse began to gallop across the field.",
  "fabulous": "We had a fabulous time at the party.",
  "lanky": "The lanky basketball player was very tall.",
  "fluently": "She speaks Spanish fluently.",
  "mysterious": "The mysterious stranger wore a black coat.",
  "brandished": "The knight brandished his sword.",
  "sardines": "We packed into the car like sardines.",
  "anguish": "He felt anguish when his pet ran away.",
  "conical": "The wizard wore a conical hat.",
  "rickety": "The rickety bridge swayed in the wind.",
  "lilt": "Her voice had a musical lilt to it.",
  "pediatric": "The pediatric doctor takes care of children.",
  "porridge": "Goldilocks ate the bear's porridge.",
  "democracy": "In a democracy, people vote for their leaders.",
  "rummage": "I had to rummage through my bag to find my keys.",
  "beige": "The living room walls are painted beige.",
  "ancestral": "We visited our ancestral home in Ireland.",
  "grimace": "He made a grimace when he tasted the medicine.",
  "gaunt": "The lost hiker looked gaunt and tired.",
  "enormous": "The enormous whale swam past our boat.",
  "geranium": "The red geranium bloomed on the windowsill.",
  "nautical": "The room had a nautical theme with boats.",
  "dubious": "I was dubious about his wild story.",
  "ebony": "The piano had beautiful ebony keys.",
  "foreign": "We tried food from a foreign country.",
  "paltry": "The paltry amount of food wasn't enough.",
  "verdict": "The jury announced their verdict.",
  "garbled": "The message was garbled and hard to understand.",
  "encourages": "My teacher encourages me to do my best.",
  "imitation": "The painting was an imitation of the original.",
  "miniature": "She collects miniature toy horses.",
  "receptionist": "The receptionist answered the phone.",
  "preamble": "The Constitution begins with a preamble.",
  "plausible": "His excuse seemed plausible.",
  "reprimanding": "Mom was reprimanding me for breaking the vase.",
  "commotion": "The fire alarm caused a commotion.",
  "oblivion": "The old song faded into oblivion.",
  "immigrants": "Many immigrants came to America for a better life.",
  "steeple": "The church steeple reached toward the sky.",
  "spectators": "The spectators cheered for their team.",
  "lanyards": "We made colorful lanyards at summer camp.",
  "suspicious": "The detective was suspicious of the suspect.",
  "parchment": "The old map was drawn on parchment.",
  "ramshackle": "The ramshackle house needed many repairs.",
  "fugitive": "The fugitive tried to escape from the police.",
  "heron": "A blue heron stood by the water.",
  "dissolving": "The sugar was dissolving in the warm tea.",
  "nomad": "The nomad traveled from place to place.",
  "billowed": "The curtains billowed in the breeze.",
  "skewer": "We put vegetables on a skewer for grilling.",
  "Berlin": "Berlin is the capital city of Germany.",
  "lunacy": "It would be lunacy to go out in this storm.",
  "conjure": "The magician tried to conjure a rabbit.",
  "bracken": "The forest floor was covered with bracken.",
  "noggin": "Use your noggin to figure out the answer.",
  "neon": "The neon sign glowed brightly at night.",
  "rakish": "He wore his hat at a rakish angle.",
  "hypnosis": "The hypnosis made him feel very relaxed.",
  "rotunda": "The rotunda had a beautiful domed ceiling.",
  "gusto": "She ate the pizza with great gusto.",
  "toiletries": "Pack your toiletries in a small bag.",
  "gleaned": "I gleaned useful information from the book.",
  "jeered": "The crowd jeered at the opposing team.",
  "winsome": "The baby had a winsome smile.",
  "prattling": "The children were prattling on about their day.",
  "galore": "There were toys galore at the store.",
  "emporium": "We visited the candy emporium downtown.",
  "atrium": "The hotel had a beautiful atrium with plants.",
  "eccentric": "My eccentric uncle collects rubber ducks.",
  "savant": "The savant could solve any math problem instantly.",

  // THREE BEE words
  "almanac": "Farmers use an almanac to plan their planting.",
  "hippies": "The hippies wore colorful clothes in the 1960s.",
  "samosas": "We ordered delicious samosas at the Indian restaurant.",
  "campaign": "The politician ran a successful campaign.",
  "pistachio": "Pistachio is my favorite ice cream flavor.",
  "mosque": "The mosque is a place of worship.",
  "zombielike": "I felt zombielike without my morning sleep.",
  "warlock": "The warlock cast a powerful spell.",
  "colossus": "The Colossus of Rhodes was a giant statue.",
  "convulsively": "She laughed convulsively at the joke.",
  "dimensional": "The movie was in three dimensional format.",
  "garishly": "The room was garishly decorated with neon colors.",
  "graffitist": "The graffitist painted murals on city walls.",
  "Everest": "Mount Everest is the tallest mountain on Earth.",
  "dexterity": "The surgeon needed great dexterity.",
  "cavorting": "The puppies were cavorting in the yard.",
  "marauder": "The marauder tried to steal from the village.",
  "conscience": "My conscience told me to tell the truth.",
  "battlements": "Guards stood on the castle battlements.",
  "deferential": "He was deferential to the elderly woman.",
  "albatross": "The albatross has the largest wingspan of any bird.",
  "khaki": "He wore khaki pants to school.",
  "opalescent": "The seashell had an opalescent shimmer.",
  "asphalt": "The workers paved the road with asphalt.",
  "Yiddish": "My grandmother speaks Yiddish.",
  "talcum": "She applied talcum powder after her bath.",
  "tranquilizer": "The vet used a tranquilizer on the wild animal.",
  "equestrian": "She competed in equestrian events with horses.",
  "plaited": "Her hair was plaited into a neat braid.",
  "monsieur": "Monsieur is French for mister.",
  "manticores": "Manticores are mythical creatures with lion bodies.",
  "prestigious": "Harvard is a prestigious university.",
  "fraidycat": "Don't be such a fraidycat about the dark.",
  "guttural": "The monster made a guttural growl.",
  "lo mein": "We ordered lo mein from the Chinese restaurant.",
  "courier": "The courier delivered the package on time.",
  "sans serif": "This font is a sans serif typeface.",
  "psyche": "The test was designed to analyze your psyche.",
  "stucco": "The house had a beautiful stucco exterior.",
  "Frankenstein": "Frankenstein is a famous novel by Mary Shelley.",
  "schema": "The teacher explained the schema for the project.",
  "et cetera": "We need paper, pencils, et cetera for class.",
  "vidimus": "The scholar found a vidimus of the ancient document.",
  "delphine": "The delphine creature resembled a dolphin.",
  "slough": "The snake began to slough off its old skin.",
  "archipelago": "Hawaii is an archipelago of islands.",
  "serape": "He wrapped himself in a colorful serape.",
  "puissance": "The knight displayed great puissance in battle.",
  "pinioning": "The wrestler was pinioning his opponent's arms.",
  "chignon": "She wore her hair in an elegant chignon.",
  "pheromone": "Insects use pheromone signals to communicate.",
  "galleon": "The Spanish galleon sailed across the ocean.",
  "magnanimous": "It was magnanimous of her to forgive him.",
  "chartreuse": "The walls were painted a bright chartreuse green.",
  "wainscoting": "The dining room had elegant wainscoting.",
  "Nehru": "He wore a Nehru jacket to the ceremony.",
  "gangly": "The gangly teenager was all arms and legs.",
  "swaggering": "He came swaggering into the room confidently.",
  "chimneys": "Smoke rose from the chimneys.",
  "riveted": "I was riveted by the exciting movie.",
  "plaid": "She wore a red plaid skirt to school.",
  "dirge": "The sad dirge played at the funeral.",
  "zeal": "She approached her work with great zeal.",
  "whittled": "Grandpa whittled a toy boat from wood.",
  "depots": "Trains stop at depots to pick up passengers.",
  "fiberglass": "The boat was made of fiberglass.",
  "salvaged": "We salvaged wood from the old barn.",
  "fissures": "The earthquake caused fissures in the ground.",
  "enthusiastic": "The enthusiastic fans cheered loudly.",
  "discipline": "Athletes need discipline to train every day.",
  "unfamiliar": "The new neighborhood was unfamiliar to me.",
  "scurrying": "Mice were scurrying across the floor.",
  "dignitaries": "Important dignitaries attended the meeting.",
  "pizzeria": "We ate at our favorite pizzeria.",
  "dismissal": "School dismissal is at three o'clock.",
  "skittish": "The skittish horse was startled by the noise.",
  "careened": "The car careened around the sharp corner.",
  "nomination": "Her nomination for class president was announced.",
  "opportunist": "The opportunist took advantage of the situation.",
  "dictatorship": "A dictatorship is ruled by one person.",
  "comrades": "The soldiers were loyal comrades.",
  "sporadic": "There was sporadic rain throughout the day.",
  "promenade": "They walked along the seaside promenade.",
  "repugnant": "The smell was absolutely repugnant.",
  "invincible": "The superhero seemed invincible.",
  "renowned": "The renowned artist displayed her paintings.",
  "parachute": "The skydiver opened her parachute.",
  "laborious": "Moving all those boxes was laborious work.",
  "appointment": "I have a doctor's appointment tomorrow.",
  "foreseeable": "There's no solution in the foreseeable future.",
  "ratify": "Congress needs to ratify the treaty.",
  "scalpel": "The surgeon used a scalpel during the operation.",
  "reclusive": "The reclusive author rarely gives interviews.",
  "compassionate": "The nurse was very compassionate with patients.",
  "bulletin": "Check the bulletin board for announcements.",
  "alfalfa": "Farmers grow alfalfa to feed their animals.",
  "officially": "The game has officially begun.",
  "crematorium": "The crematorium is next to the cemetery.",
  "bayonet": "The soldier attached a bayonet to his rifle.",
  "amicable": "They reached an amicable agreement.",
  "exuberant": "The exuberant children ran through the park.",
  "beautician": "The beautician styled her hair for the wedding.",
  "equations": "We solved math equations in class today.",
  "assignment": "The homework assignment is due Friday.",
  "ultimatum": "She gave him an ultimatum to clean his room.",
  "whinnying": "The horse was whinnying in the stable.",
  "squalor": "The abandoned house was in total squalor.",
  "memoirs": "The actor wrote memoirs about her life.",
  "cylinders": "The engine has six cylinders.",
  "ominous": "The dark clouds looked ominous.",
  "muffler": "The car needs a new muffler.",
  "syndrome": "The doctor diagnosed the rare syndrome.",
  "premises": "Smoking is not allowed on these premises.",
  "safari": "We went on a safari in Africa.",
  "lasagna": "Grandma makes the best lasagna.",
  "substantially": "The price has increased substantially.",
  "mercantile": "The old mercantile store sold everything.",
  "formidable": "The formidable opponent was hard to beat.",
  "propaganda": "The poster was wartime propaganda.",
  "marquee": "The movie title was on the theater marquee.",
  "proficient": "She is proficient in three languages.",
  "compunction": "He felt no compunction about lying.",
  "emphatically": "She emphatically denied the accusation.",
  "hyperventilated": "I nearly hyperventilated from excitement.",
  "ostracism": "Bullying can lead to social ostracism.",
  "onslaught": "We prepared for the onslaught of winter storms.",
  "ruefully": "He ruefully admitted his mistake.",
  "misanthrope": "The misanthrope preferred being alone.",
  "prototype": "The inventor built a prototype of her design.",
  "cravenly": "He cravenly ran away from the fight.",
  "mulberry": "We picked berries from the mulberry bush.",
  "hypocritical": "It would be hypocritical to judge others.",
  "chlorine": "The pool smelled like chlorine.",
  "traumatic": "The accident was a traumatic experience.",
  "receipts": "Keep your receipts for returns.",
  "solemnly": "She solemnly promised to tell the truth.",
  "begrudge": "I don't begrudge him his success.",
  "contentious": "The contentious debate lasted for hours.",
  "precocious": "The precocious child could read at age three.",
  "ensemble": "The jazz ensemble performed beautifully.",
  "cadre": "A small cadre of scientists worked on the project.",
  "lye": "Soap can be made from lye and fat.",
  "belfry": "Bats lived in the church belfry.",
  "lacrosse": "My sister plays lacrosse after school.",
  "sluice": "Water flowed through the sluice gate.",
  "cajolery": "No amount of cajolery would change her mind.",
  "vigilance": "The guards maintained constant vigilance.",
  "residuals": "The actor earns residuals from reruns.",
  "boutique": "She bought a dress at the boutique.",
  "peroxide": "Peroxide can be used to clean wounds.",
  "aristocracy": "The aristocracy lived in grand estates.",
  "apocalypse": "The movie was about surviving an apocalypse.",
  "tuberculosis": "Tuberculosis is a serious lung disease.",
  "barricade": "They built a barricade across the street.",
  "confreres": "The doctor consulted with his confreres.",
  "anonymously": "The donation was made anonymously.",
  "unparalleled": "Her talent is unparalleled in the industry.",
  "barrette": "She wore a sparkly barrette in her hair.",
  "chassis": "The car's chassis was made of steel.",
  "junket": "The senator went on a junket to Europe.",
  "quandary": "I'm in a quandary about which college to choose.",
  "Erie": "Lake Erie is one of the Great Lakes.",
  "gingham": "She wore a blue gingham dress.",
  "silhouette": "I saw his silhouette against the window.",
  "auxiliary": "The hospital has an auxiliary staff of volunteers.",
  "thesaurus": "Use a thesaurus to find synonyms.",
  "patriarchs": "The patriarchs of the family gathered together.",
  "chandelier": "The crystal chandelier sparkled above us.",
  "dulce": "Dulce de leche is a sweet caramel sauce.",
  "concierge": "The hotel concierge recommended a restaurant.",
  "latticework": "The fence had beautiful wooden latticework.",
  "hibiscus": "The hibiscus flower is bright red.",
  "tamale": "Grandma made a delicious tamale for dinner.",
  "maracas": "She shook the maracas to the music.",
  "gyroplane": "The gyroplane flew over the field.",
  "burpees": "We did twenty burpees in gym class.",
  "Adriatic": "The Adriatic Sea is near Italy.",
  "piccolo": "She plays the piccolo in the band.",
  "au revoir": "Au revoir means goodbye in French.",
  "tulle": "The dress was made of delicate tulle.",
  "boll weevil": "The boll weevil destroyed the cotton crop.",
  "camphor": "The smell of camphor filled the room.",
  "Tucson": "Tucson is a city in Arizona.",
  "paparazzi": "The paparazzi followed the celebrity.",
  "pumpernickel": "I made a sandwich with pumpernickel bread.",
  "pogrom": "The history book described the terrible pogrom.",
  "bursitis": "The athlete was diagnosed with bursitis.",
  "cycads": "Cycads are ancient plants that look like palms.",
  "sarsaparilla": "The old general store sold sarsaparilla drinks.",
  "cannelloni": "We ordered cannelloni at the Italian restaurant.",
  "boulangerie": "We bought croissants at the French boulangerie.",
  "bronchitis": "She stayed home sick with bronchitis.",
  "Oswego": "Oswego is a city in New York state.",
  "diphtheria": "Vaccines help prevent diphtheria.",
  "baklava": "The Greek baklava was sweet and flaky.",
  "corbels": "The old building had decorative stone corbels.",
  "trebuchets": "Medieval armies used trebuchets to attack castles.",
  "Kilimanjaro": "Mount Kilimanjaro is in Tanzania.",
  "protege": "The famous chef took on a young protege.",
  "hors d'oeuvres": "We served hors d'oeuvres before dinner.",
  "maquisards": "The maquisards were French resistance fighters.",
  "Aubusson": "The Aubusson tapestry was very valuable.",
  "Charolais": "The Charolais cattle are white in color."
};

// Export for use in main app
const WORD_LISTS = {
  one: ONE_BEE,
  two: TWO_BEE,
  three: THREE_BEE,
  all: [...ONE_BEE, ...TWO_BEE, ...THREE_BEE]
};
